#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

Eloquent\Asplode\Asplode::install();

use React\EventLoop\Factory;
use Recoil\Amqp\ConnectionOptions;
use Recoil\Amqp\ReactConnection;

$loop = Factory::create();
$options = ConnectionOptions::create();

$connection = new ReactConnection($loop, $options);
$connection->connect();

$loop->run();
