#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

Eloquent\Asplode\Asplode::install();

use React\EventLoop\Factory;
use Recoil\Amqp\ConnectionException;
use Recoil\Amqp\ConnectionOptions;
use Recoil\Amqp\v091\React\StreamConnector;

$loop = Factory::create();

$connector = new StreamConnector(
    ConnectionOptions::create(),
    $loop
);

$connector
    ->connect()
    ->then(
        function ($connection) {
            var_dump($connection);
        },
        function ($error) {
            if ($error instanceof ConnectionException) {
                echo $error->getMessage() . PHP_EOL;
            } else {
                echo $error . PHP_EOL;
            }
        }
    );

$loop->run();
