#!/usr/bin/env php
<?php
require __DIR__ . '/../vendor/autoload.php';

Eloquent\Asplode\Asplode::install();

use Recoil\Amqp\ConnectionOptions;
use Recoil\Amqp\ExchangeType;
use Recoil\Amqp\QueueOptions;
use Recoil\Amqp\v091\Amqp091Connector;
use Recoil\Recoil;

Recoil::run(
    function () {
        $options    = ConnectionOptions::create();
        $connector  = new Amqp091Connector(yield Recoil::eventLoop());
        $connection = (yield $connector->connect($options));

        $channel = (yield $connection->channel());
        echo 'Opened channel #' . $channel->id() . PHP_EOL;

        $exchange = (yield $channel->exchange(
            'foo',
            ExchangeType::DIRECT()
        ));

        $queue = (yield $channel->queue());

        yield $queue->bind(
            $exchange,
            $queue->name()
        );

        yield $queue->unbind(
            $exchange,
            $queue->name()
        );

        $connection->close();
    }
);
